go:
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

sudo: false
language: go

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - make
